/// autogenerated analytical inverse kinematics code from ikfast program part of OpenRAVE
/// \author Rosen Diankov
///
/// Licensed under the Apache License, Version 2.0 (the "License");
/// you may not use this file except in compliance with the License.
/// You may obtain a copy of the License at
///     http://www.apache.org/licenses/LICENSE-2.0
/// 
/// Unless required by applicable law or agreed to in writing, software
/// distributed under the License is distributed on an "AS IS" BASIS,
/// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
/// See the License for the specific language governing permissions and
/// limitations under the License.
///
/// ikfast version 61 generated on 2013-05-30 22:49:01.616024
/// To compile with gcc:
///     gcc -lstdc++ ik.cpp
/// To compile without any main function as a shared object (might need -llapack):
///     gcc -fPIC -lstdc++ -DIKFAST_NO_MAIN -DIKFAST_CLIBRARY -shared -Wl,-soname,libik.so -o libik.so ik.cpp
#define IKFAST_HAS_LIBRARY
#include "ikfast.h" // found inside share/openrave-X.Y/python/ikfast.h
using namespace ikfast;

// check if the included ikfast version matches what this file was compiled with
#define IKFAST_COMPILE_ASSERT(x) extern int __dummy[(int)x]
IKFAST_COMPILE_ASSERT(IKFAST_VERSION==61);

#include <cmath>
#include <vector>
#include <limits>
#include <algorithm>
#include <complex>

#define IKFAST_STRINGIZE2(s) #s
#define IKFAST_STRINGIZE(s) IKFAST_STRINGIZE2(s)

#ifndef IKFAST_ASSERT
#include <stdexcept>
#include <sstream>
#include <iostream>

#ifdef _MSC_VER
#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __FUNCDNAME__
#endif
#endif

#ifndef __PRETTY_FUNCTION__
#define __PRETTY_FUNCTION__ __func__
#endif

#define IKFAST_ASSERT(b) { if( !(b) ) { std::stringstream ss; ss << "ikfast exception: " << __FILE__ << ":" << __LINE__ << ": " <<__PRETTY_FUNCTION__ << ": Assertion '" << #b << "' failed"; throw std::runtime_error(ss.str()); } }

#endif

#if defined(_MSC_VER)
#define IKFAST_ALIGNED16(x) __declspec(align(16)) x
#else
#define IKFAST_ALIGNED16(x) x __attribute((aligned(16)))
#endif

#define IK2PI  ((IkReal)6.28318530717959)
#define IKPI  ((IkReal)3.14159265358979)
#define IKPI_2  ((IkReal)1.57079632679490)

#ifdef _MSC_VER
#ifndef isnan
#define isnan _isnan
#endif
#endif // _MSC_VER

// lapack routines
extern "C" {
  void dgetrf_ (const int* m, const int* n, double* a, const int* lda, int* ipiv, int* info);
  void zgetrf_ (const int* m, const int* n, std::complex<double>* a, const int* lda, int* ipiv, int* info);
  void dgetri_(const int* n, const double* a, const int* lda, int* ipiv, double* work, const int* lwork, int* info);
  void dgesv_ (const int* n, const int* nrhs, double* a, const int* lda, int* ipiv, double* b, const int* ldb, int* info);
  void dgetrs_(const char *trans, const int *n, const int *nrhs, double *a, const int *lda, int *ipiv, double *b, const int *ldb, int *info);
  void dgeev_(const char *jobvl, const char *jobvr, const int *n, double *a, const int *lda, double *wr, double *wi,double *vl, const int *ldvl, double *vr, const int *ldvr, double *work, const int *lwork, int *info);
}

using namespace std; // necessary to get std math routines

#ifdef IKFAST_NAMESPACE
namespace IKFAST_NAMESPACE {
#endif

inline float IKabs(float f) { return fabsf(f); }
inline double IKabs(double f) { return fabs(f); }

inline float IKsqr(float f) { return f*f; }
inline double IKsqr(double f) { return f*f; }

inline float IKlog(float f) { return logf(f); }
inline double IKlog(double f) { return log(f); }

// allows asin and acos to exceed 1
#ifndef IKFAST_SINCOS_THRESH
#define IKFAST_SINCOS_THRESH ((IkReal)0.000001)
#endif

// used to check input to atan2 for degenerate cases
#ifndef IKFAST_ATAN2_MAGTHRESH
#define IKFAST_ATAN2_MAGTHRESH ((IkReal)2e-6)
#endif

// minimum distance of separate solutions
#ifndef IKFAST_SOLUTION_THRESH
#define IKFAST_SOLUTION_THRESH ((IkReal)1e-6)
#endif

inline float IKasin(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(-IKPI_2);
else if( f >= 1 ) return float(IKPI_2);
return asinf(f);
}
inline double IKasin(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return -IKPI_2;
else if( f >= 1 ) return IKPI_2;
return asin(f);
}

// return positive value in [0,y)
inline float IKfmod(float x, float y)
{
    while(x < 0) {
        x += y;
    }
    return fmodf(x,y);
}

// return positive value in [0,y)
inline double IKfmod(double x, double y)
{
    while(x < 0) {
        x += y;
    }
    return fmod(x,y);
}

inline float IKacos(float f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return float(IKPI);
else if( f >= 1 ) return float(0);
return acosf(f);
}
inline double IKacos(double f)
{
IKFAST_ASSERT( f > -1-IKFAST_SINCOS_THRESH && f < 1+IKFAST_SINCOS_THRESH ); // any more error implies something is wrong with the solver
if( f <= -1 ) return IKPI;
else if( f >= 1 ) return 0;
return acos(f);
}
inline float IKsin(float f) { return sinf(f); }
inline double IKsin(double f) { return sin(f); }
inline float IKcos(float f) { return cosf(f); }
inline double IKcos(double f) { return cos(f); }
inline float IKtan(float f) { return tanf(f); }
inline double IKtan(double f) { return tan(f); }
inline float IKsqrt(float f) { if( f <= 0.0f ) return 0.0f; return sqrtf(f); }
inline double IKsqrt(double f) { if( f <= 0.0 ) return 0.0; return sqrt(f); }
inline float IKatan2(float fy, float fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return float(IKPI_2);
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2f(fy,fx);
}
inline double IKatan2(double fy, double fx) {
    if( isnan(fy) ) {
        IKFAST_ASSERT(!isnan(fx)); // if both are nan, probably wrong value will be returned
        return IKPI_2;
    }
    else if( isnan(fx) ) {
        return 0;
    }
    return atan2(fy,fx);
}

inline float IKsign(float f) {
    if( f > 0 ) {
        return float(1);
    }
    else if( f < 0 ) {
        return float(-1);
    }
    return 0;
}

inline double IKsign(double f) {
    if( f > 0 ) {
        return 1.0;
    }
    else if( f < 0 ) {
        return -1.0;
    }
    return 0;
}

/// solves the forward kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API void ComputeFk(const IkReal* j, IkReal* eetrans, IkReal* eerot) {
IkReal x0,x1,x2,x3,x4,x5,x6,x7;
x0=IKcos(j[0]);
x1=IKsin(j[1]);
x2=IKcos(j[2]);
x3=IKsin(j[0]);
x4=IKcos(j[1]);
x5=IKsin(j[2]);
x6=((IkReal(0.106000000000000))*(x1));
x7=((IkReal(0.106000000000000))*(x4));
IkReal x8=((x0)*(x6));
eetrans[0]=((x8)+(((x2)*(x8)))+(((x0)*(x5)*(x7))));
IkReal x9=((x3)*(x6));
eetrans[1]=((((x3)*(x5)*(x7)))+(x9)+(((x2)*(x9))));
eetrans[2]=((IkReal(0.0605000000000000))+(x7)+(((x2)*(x7)))+(((IkReal(-1.00000000000000))*(x5)*(x6))));
}

IKFAST_API int GetNumFreeParameters() { return 1; }
IKFAST_API int* GetFreeParameters() { static int freeparams[] = {3}; return freeparams; }
IKFAST_API int GetNumJoints() { return 4; }

IKFAST_API int GetIkRealSize() { return sizeof(IkReal); }

IKFAST_API int GetIkType() { return 0x33000003; }

class IKSolver {
public:
IkReal j0,cj0,sj0,htj0,j1,cj1,sj1,htj1,j2,cj2,sj2,htj2,j3,cj3,sj3,htj3,new_px,px,npx,new_py,py,npy,new_pz,pz,npz,pp;
unsigned char _ij0[2], _nj0,_ij1[2], _nj1,_ij2[2], _nj2,_ij3[2], _nj3;

bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
j0=numeric_limits<IkReal>::quiet_NaN(); _ij0[0] = -1; _ij0[1] = -1; _nj0 = -1; j1=numeric_limits<IkReal>::quiet_NaN(); _ij1[0] = -1; _ij1[1] = -1; _nj1 = -1; j2=numeric_limits<IkReal>::quiet_NaN(); _ij2[0] = -1; _ij2[1] = -1; _nj2 = -1;  _ij3[0] = -1; _ij3[1] = -1; _nj3 = 0; 
for(int dummyiter = 0; dummyiter < 1; ++dummyiter) {
    solutions.Clear();
j3=pfree[0]; cj3=cos(pfree[0]); sj3=sin(pfree[0]);
px = eetrans[0]; py = eetrans[1]; pz = eetrans[2];

new_px=py;
new_py=((IkReal(-1.00000000000000))*(px));
new_pz=((IkReal(-0.0605000000000000))+(pz));
px = new_px; py = new_py; pz = new_pz;
pp=(((px)*(px))+((py)*(py))+((pz)*(pz)));
{
IkReal j2array[2], cj2array[2], sj2array[2];
bool j2valid[2]={false};
_nj2 = 2;
cj2array[0]=((IkReal(-1.00000000000000))+(((IkReal(44.4998220007120))*(pp))));
if( cj2array[0] >= -1-IKFAST_SINCOS_THRESH && cj2array[0] <= 1+IKFAST_SINCOS_THRESH )
{
    j2valid[0] = j2valid[1] = true;
    j2array[0] = IKacos(cj2array[0]);
    sj2array[0] = IKsin(j2array[0]);
    cj2array[1] = cj2array[0];
    j2array[1] = -j2array[0];
    sj2array[1] = -sj2array[0];
}
else if( isnan(cj2array[0]) )
{
    // probably any value will work
    j2valid[0] = true;
    cj2array[0] = 1; sj2array[0] = 0; j2array[0] = 0;
}
for(int ij2 = 0; ij2 < 2; ++ij2)
{
if( !j2valid[ij2] )
{
    continue;
}
_ij2[0] = ij2; _ij2[1] = -1;
for(int iij2 = ij2+1; iij2 < 2; ++iij2)
{
if( j2valid[iij2] && IKabs(cj2array[ij2]-cj2array[iij2]) < IKFAST_SOLUTION_THRESH && IKabs(sj2array[ij2]-sj2array[iij2]) < IKFAST_SOLUTION_THRESH )
{
    j2valid[iij2]=false; _ij2[1] = iij2; break; 
}
}
j2 = j2array[ij2]; cj2 = cj2array[ij2]; sj2 = sj2array[ij2];

{
IkReal j0array[2], cj0array[2], sj0array[2];
bool j0valid[2]={false};
_nj0 = 2;
if( IKabs(((IkReal(-1.00000000000000))*(px))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((IkReal(-1.00000000000000))*(py))) < IKFAST_ATAN2_MAGTHRESH )
    continue;
IkReal x10=IKatan2(((IkReal(-1.00000000000000))*(px)), ((IkReal(-1.00000000000000))*(py)));
j0array[0]=((IkReal(-1.00000000000000))*(x10));
sj0array[0]=IKsin(j0array[0]);
cj0array[0]=IKcos(j0array[0]);
j0array[1]=((IkReal(3.14159265358979))+(((IkReal(-1.00000000000000))*(x10))));
sj0array[1]=IKsin(j0array[1]);
cj0array[1]=IKcos(j0array[1]);
if( j0array[0] > IKPI )
{
    j0array[0]-=IK2PI;
}
else if( j0array[0] < -IKPI )
{    j0array[0]+=IK2PI;
}
j0valid[0] = true;
if( j0array[1] > IKPI )
{
    j0array[1]-=IK2PI;
}
else if( j0array[1] < -IKPI )
{    j0array[1]+=IK2PI;
}
j0valid[1] = true;
for(int ij0 = 0; ij0 < 2; ++ij0)
{
if( !j0valid[ij0] )
{
    continue;
}
_ij0[0] = ij0; _ij0[1] = -1;
for(int iij0 = ij0+1; iij0 < 2; ++iij0)
{
if( j0valid[iij0] && IKabs(cj0array[ij0]-cj0array[iij0]) < IKFAST_SOLUTION_THRESH && IKabs(sj0array[ij0]-sj0array[iij0]) < IKFAST_SOLUTION_THRESH )
{
    j0valid[iij0]=false; _ij0[1] = iij0; break; 
}
}
j0 = j0array[ij0]; cj0 = cj0array[ij0]; sj0 = sj0array[ij0];

{
IkReal dummyeval[1];
IkReal gconst0;
IkReal x11=((IkReal(2809.00000000000))*(cj0)*(py));
IkReal x12=((IkReal(2809.00000000000))*(px)*(sj0));
gconst0=IKsign(((((IkReal(-1.00000000000000))*(x12)))+(((IkReal(-2809.00000000000))*(pz)*(sj2)))+(((IkReal(-1.00000000000000))*(cj2)*(x12)))+(x11)+(((cj2)*(x11)))));
IkReal x13=((cj0)*(py));
IkReal x14=((IkReal(1.00000000000000))*(px)*(sj0));
dummyeval[0]=((((IkReal(-1.00000000000000))*(x14)))+(((IkReal(-1.00000000000000))*(cj2)*(x14)))+(x13)+(((cj2)*(x13)))+(((IkReal(-1.00000000000000))*(pz)*(sj2))));
if( IKabs(dummyeval[0]) < 0.0000010000000000  )
{
{
IkReal dummyeval[1];
IkReal x15=((IkReal(1.00000000000000))*(pz));
dummyeval[0]=((((IkReal(-1.00000000000000))*(cj0)*(py)*(sj2)))+(((IkReal(-1.00000000000000))*(x15)))+(((px)*(sj0)*(sj2)))+(((IkReal(-1.00000000000000))*(cj2)*(x15))));
if( IKabs(dummyeval[0]) < 0.0000010000000000  )
{
{
IkReal evalcond[5];
IkReal x16=((IkReal(1.00000000000000))*(sj0));
evalcond[0]=((IkReal(-3.14159265358979))+(IKfmod(((IkReal(1.11022302462516e-16))+(j2)), IkReal(6.28318530717959))));
evalcond[1]=((IkReal(-1.00000000000000))*(pp));
evalcond[2]=((((IkReal(-1.00000000000000))*(py)*(x16)))+(((IkReal(-1.00000000000000))*(cj0)*(px))));
evalcond[3]=pz;
evalcond[4]=((((IkReal(-1.00000000000000))*(px)*(x16)))+(((cj0)*(py))));
if( IKabs(evalcond[0]) < 0.0000010000000000  && IKabs(evalcond[1]) < 0.0000010000000000  && IKabs(evalcond[2]) < 0.0000010000000000  && IKabs(evalcond[3]) < 0.0000010000000000  && IKabs(evalcond[4]) < 0.0000010000000000  )
{
{
IkReal dummyeval[1];
IkReal gconst1;
gconst1=IKsign(((((IkReal(106.000000000000))*(cj0)*(px)*(py)*(sj0)))+(((IkReal(-53.0000000000000))*((px)*(px))*((sj0)*(sj0))))+(((IkReal(-53.0000000000000))*((pz)*(pz))))+(((IkReal(-53.0000000000000))*((cj0)*(cj0))*((py)*(py))))));
dummyeval[0]=((((IkReal(-1.00000000000000))*((px)*(px))*((sj0)*(sj0))))+(((IkReal(-1.00000000000000))*((pz)*(pz))))+(((IkReal(2.00000000000000))*(cj0)*(px)*(py)*(sj0)))+(((IkReal(-1.00000000000000))*((cj0)*(cj0))*((py)*(py)))));
if( IKabs(dummyeval[0]) < 0.0000010000000000  )
{
continue;

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x17=((IkReal(250.000000000000))*(pp));
if( IKabs(((gconst1)*(((((cj0)*(py)*(x17)))+(((IkReal(-1.00000000000000))*(px)*(sj0)*(x17))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((IkReal(-250.000000000000))*(gconst1)*(pp)*(pz))) < IKFAST_ATAN2_MAGTHRESH )
    continue;
j1array[0]=IKatan2(((gconst1)*(((((cj0)*(py)*(x17)))+(((IkReal(-1.00000000000000))*(px)*(sj0)*(x17)))))), ((IkReal(-250.000000000000))*(gconst1)*(pp)*(pz)));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[3];
IkReal x18=IKcos(j1);
IkReal x19=IKsin(j1);
IkReal x20=((cj0)*(py));
IkReal x21=((px)*(sj0));
IkReal x22=((IkReal(0.212000000000000))*(x19));
IkReal x23=((pz)*(x18));
evalcond[0]=((((x18)*(x20)))+(((pz)*(x19)))+(((IkReal(-1.00000000000000))*(x18)*(x21))));
evalcond[1]=((((x21)*(x22)))+(((IkReal(-1.00000000000000))*(x20)*(x22)))+(((IkReal(-1.00000000000000))*(pp)))+(((IkReal(0.212000000000000))*(x23))));
evalcond[2]=((((x19)*(x21)))+(((IkReal(-1.00000000000000))*(x19)*(x20)))+(x23));
if( IKabs(evalcond[0]) > 0.000001  || IKabs(evalcond[1]) > 0.000001  || IKabs(evalcond[2]) > 0.000001  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(4);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j3;
vinfos[3].indices[0] = _ij3[0];
vinfos[3].indices[1] = _ij3[1];
vinfos[3].maxsolutions = _nj3;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
if( 1 )
{
continue;

} else
{
}
}
}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x24=((IkReal(53.0000000000000))*(sj2));
IkReal x25=((px)*(sj0));
IkReal x26=((IkReal(5.61800000000000))*(sj2));
IkReal x27=((IkReal(53.0000000000000))*(pz));
IkReal x28=((cj0)*(py));
IkReal x29=((IkReal(500.000000000000))*(pz));
IkReal x30=((IkReal(26500.0000000000))*(sj2));
IkReal x31=((IkReal(26500.0000000000))*(pz));
if( IKabs(((((IKabs(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25)))))):(IkReal)1.0e30))*(((((IkReal(-1.00000000000000))*(x25)*(x29)))+(((x28)*(x29)))+(x26)+(((cj2)*(x26))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((((IKabs(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30)))))):(IkReal)1.0e30))*(((((IkReal(-250000.000000000))*((pz)*(pz))))+(((IkReal(2809.00000000000))*((sj2)*(sj2)))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(IKsqr(((((IKabs(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25)))))):(IkReal)1.0e30))*(((((IkReal(-1.00000000000000))*(x25)*(x29)))+(((x28)*(x29)))+(x26)+(((cj2)*(x26)))))))+IKsqr(((((IKabs(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30)))))):(IkReal)1.0e30))*(((((IkReal(-250000.000000000))*((pz)*(pz))))+(((IkReal(2809.00000000000))*((sj2)*(sj2))))))))-1) <= IKFAST_SINCOS_THRESH )
    continue;
j1array[0]=IKatan2(((((IKabs(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x27)))+(((IkReal(-1.00000000000000))*(cj2)*(x27)))+(((IkReal(-1.00000000000000))*(x24)*(x28)))+(((x24)*(x25)))))):(IkReal)1.0e30))*(((((IkReal(-1.00000000000000))*(x25)*(x29)))+(((x28)*(x29)))+(x26)+(((cj2)*(x26)))))), ((((IKabs(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30))))) != 0)?((IkReal)1/(((((IkReal(-1.00000000000000))*(x28)*(x30)))+(((IkReal(-1.00000000000000))*(x31)))+(((IkReal(-1.00000000000000))*(cj2)*(x31)))+(((x25)*(x30)))))):(IkReal)1.0e30))*(((((IkReal(-250000.000000000))*((pz)*(pz))))+(((IkReal(2809.00000000000))*((sj2)*(sj2))))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x32=IKcos(j1);
IkReal x33=IKsin(j1);
IkReal x34=((cj0)*(py));
IkReal x35=((IkReal(0.106000000000000))*(cj2));
IkReal x36=((px)*(sj0));
IkReal x37=((IkReal(0.212000000000000))*(x33));
IkReal x38=((IkReal(0.106000000000000))*(x32));
IkReal x39=((IkReal(0.106000000000000))*(x33));
IkReal x40=((pz)*(x32));
evalcond[0]=((((IkReal(-1.00000000000000))*(x38)))+(((IkReal(-1.00000000000000))*(x32)*(x35)))+(pz)+(((sj2)*(x39))));
evalcond[1]=((((IkReal(0.106000000000000))*(sj2)))+(((pz)*(x33)))+(((x32)*(x34)))+(((IkReal(-1.00000000000000))*(x32)*(x36))));
evalcond[2]=((((IkReal(0.212000000000000))*(x40)))+(((x36)*(x37)))+(((IkReal(-1.00000000000000))*(pp)))+(((IkReal(-1.00000000000000))*(x34)*(x37))));
evalcond[3]=((IkReal(-0.106000000000000))+(((IkReal(-1.00000000000000))*(x35)))+(x40)+(((IkReal(-1.00000000000000))*(x33)*(x34)))+(((x33)*(x36))));
evalcond[4]=((((IkReal(-1.00000000000000))*(x36)))+(x39)+(x34)+(((sj2)*(x38)))+(((x33)*(x35))));
if( IKabs(evalcond[0]) > 0.000001  || IKabs(evalcond[1]) > 0.000001  || IKabs(evalcond[2]) > 0.000001  || IKabs(evalcond[3]) > 0.000001  || IKabs(evalcond[4]) > 0.000001  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(4);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j3;
vinfos[3].indices[0] = _ij3[0];
vinfos[3].indices[1] = _ij3[1];
vinfos[3].maxsolutions = _nj3;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}

} else
{
{
IkReal j1array[1], cj1array[1], sj1array[1];
bool j1valid[1]={false};
_nj1 = 1;
IkReal x41=((IkReal(26500.0000000000))*(pz));
IkReal x42=((IkReal(13250.0000000000))*(pp));
if( IKabs(((gconst0)*(((((pz)*(x41)))+(((IkReal(-1.00000000000000))*(x42)))+(((IkReal(-1.00000000000000))*(cj2)*(x42))))))) < IKFAST_ATAN2_MAGTHRESH && IKabs(((gconst0)*(((((cj0)*(py)*(x41)))+(((IkReal(-1.00000000000000))*(px)*(sj0)*(x41)))+(((IkReal(-1.00000000000000))*(sj2)*(x42))))))) < IKFAST_ATAN2_MAGTHRESH )
    continue;
j1array[0]=IKatan2(((gconst0)*(((((pz)*(x41)))+(((IkReal(-1.00000000000000))*(x42)))+(((IkReal(-1.00000000000000))*(cj2)*(x42)))))), ((gconst0)*(((((cj0)*(py)*(x41)))+(((IkReal(-1.00000000000000))*(px)*(sj0)*(x41)))+(((IkReal(-1.00000000000000))*(sj2)*(x42)))))));
sj1array[0]=IKsin(j1array[0]);
cj1array[0]=IKcos(j1array[0]);
if( j1array[0] > IKPI )
{
    j1array[0]-=IK2PI;
}
else if( j1array[0] < -IKPI )
{    j1array[0]+=IK2PI;
}
j1valid[0] = true;
for(int ij1 = 0; ij1 < 1; ++ij1)
{
if( !j1valid[ij1] )
{
    continue;
}
_ij1[0] = ij1; _ij1[1] = -1;
for(int iij1 = ij1+1; iij1 < 1; ++iij1)
{
if( j1valid[iij1] && IKabs(cj1array[ij1]-cj1array[iij1]) < IKFAST_SOLUTION_THRESH && IKabs(sj1array[ij1]-sj1array[iij1]) < IKFAST_SOLUTION_THRESH )
{
    j1valid[iij1]=false; _ij1[1] = iij1; break; 
}
}
j1 = j1array[ij1]; cj1 = cj1array[ij1]; sj1 = sj1array[ij1];
{
IkReal evalcond[5];
IkReal x43=IKcos(j1);
IkReal x44=IKsin(j1);
IkReal x45=((cj0)*(py));
IkReal x46=((IkReal(0.106000000000000))*(cj2));
IkReal x47=((px)*(sj0));
IkReal x48=((IkReal(0.212000000000000))*(x44));
IkReal x49=((IkReal(0.106000000000000))*(x43));
IkReal x50=((IkReal(0.106000000000000))*(x44));
IkReal x51=((pz)*(x43));
evalcond[0]=((((sj2)*(x50)))+(((IkReal(-1.00000000000000))*(x49)))+(((IkReal(-1.00000000000000))*(x43)*(x46)))+(pz));
evalcond[1]=((((IkReal(0.106000000000000))*(sj2)))+(((pz)*(x44)))+(((x43)*(x45)))+(((IkReal(-1.00000000000000))*(x43)*(x47))));
evalcond[2]=((((x47)*(x48)))+(((IkReal(0.212000000000000))*(x51)))+(((IkReal(-1.00000000000000))*(x45)*(x48)))+(((IkReal(-1.00000000000000))*(pp))));
evalcond[3]=((IkReal(-0.106000000000000))+(((IkReal(-1.00000000000000))*(x46)))+(x51)+(((IkReal(-1.00000000000000))*(x44)*(x45)))+(((x44)*(x47))));
evalcond[4]=((((IkReal(-1.00000000000000))*(x47)))+(((sj2)*(x49)))+(x45)+(x50)+(((x44)*(x46))));
if( IKabs(evalcond[0]) > 0.000001  || IKabs(evalcond[1]) > 0.000001  || IKabs(evalcond[2]) > 0.000001  || IKabs(evalcond[3]) > 0.000001  || IKabs(evalcond[4]) > 0.000001  )
{
continue;
}
}

{
std::vector<IkSingleDOFSolutionBase<IkReal> > vinfos(4);
vinfos[0].jointtype = 1;
vinfos[0].foffset = j0;
vinfos[0].indices[0] = _ij0[0];
vinfos[0].indices[1] = _ij0[1];
vinfos[0].maxsolutions = _nj0;
vinfos[1].jointtype = 1;
vinfos[1].foffset = j1;
vinfos[1].indices[0] = _ij1[0];
vinfos[1].indices[1] = _ij1[1];
vinfos[1].maxsolutions = _nj1;
vinfos[2].jointtype = 1;
vinfos[2].foffset = j2;
vinfos[2].indices[0] = _ij2[0];
vinfos[2].indices[1] = _ij2[1];
vinfos[2].maxsolutions = _nj2;
vinfos[3].jointtype = 1;
vinfos[3].foffset = j3;
vinfos[3].indices[0] = _ij3[0];
vinfos[3].indices[1] = _ij3[1];
vinfos[3].maxsolutions = _nj3;
std::vector<int> vfree(0);
solutions.AddSolution(vinfos,vfree);
}
}
}

}

}
}
}
}
}
}
return solutions.GetNumSolutions()>0;
}
};


/// solves the inverse kinematics equations.
/// \param pfree is an array specifying the free joints of the chain.
IKFAST_API bool ComputeIk(const IkReal* eetrans, const IkReal* eerot, const IkReal* pfree, IkSolutionListBase<IkReal>& solutions) {
IKSolver solver;
return solver.ComputeIk(eetrans,eerot,pfree,solutions);
}

IKFAST_API const char* GetKinematicsHash() { return "<robot:genericrobot - turtlebot_arm (265447a7107bcf962ec9799cc968ce3e)>"; }

IKFAST_API const char* GetIkFastVersion() { return IKFAST_STRINGIZE(IKFAST_VERSION); }

#ifdef IKFAST_NAMESPACE
} // end namespace
#endif

#ifndef IKFAST_NO_MAIN
#include <stdio.h>
#include <stdlib.h>
#ifdef IKFAST_NAMESPACE
using namespace IKFAST_NAMESPACE;
#endif
int main(int argc, char** argv)
{
    if( argc != 12+GetNumFreeParameters()+1 ) {
        printf("\nUsage: ./ik r00 r01 r02 t0 r10 r11 r12 t1 r20 r21 r22 t2 free0 ...\n\n"
               "Returns the ik solutions given the transformation of the end effector specified by\n"
               "a 3x3 rotation R (rXX), and a 3x1 translation (tX).\n"
               "There are %d free parameters that have to be specified.\n\n",GetNumFreeParameters());
        return 1;
    }

    IkSolutionList<IkReal> solutions;
    std::vector<IkReal> vfree(GetNumFreeParameters());
    IkReal eerot[9],eetrans[3];
    eerot[0] = atof(argv[1]); eerot[1] = atof(argv[2]); eerot[2] = atof(argv[3]); eetrans[0] = atof(argv[4]);
    eerot[3] = atof(argv[5]); eerot[4] = atof(argv[6]); eerot[5] = atof(argv[7]); eetrans[1] = atof(argv[8]);
    eerot[6] = atof(argv[9]); eerot[7] = atof(argv[10]); eerot[8] = atof(argv[11]); eetrans[2] = atof(argv[12]);
    for(std::size_t i = 0; i < vfree.size(); ++i)
        vfree[i] = atof(argv[13+i]);
    bool bSuccess = ComputeIk(eetrans, eerot, vfree.size() > 0 ? &vfree[0] : NULL, solutions);

    if( !bSuccess ) {
        fprintf(stderr,"Failed to get ik solution\n");
        return -1;
    }

    printf("Found %d ik solutions:\n", (int)solutions.GetNumSolutions());
    std::vector<IkReal> solvalues(GetNumJoints());
    for(std::size_t i = 0; i < solutions.GetNumSolutions(); ++i) {
        const IkSolutionBase<IkReal>& sol = solutions.GetSolution(i);
        printf("sol%d (free=%d): ", (int)i, (int)sol.GetFree().size());
        std::vector<IkReal> vsolfree(sol.GetFree().size());
        sol.GetSolution(&solvalues[0],vsolfree.size()>0?&vsolfree[0]:NULL);
        for( std::size_t j = 0; j < solvalues.size(); ++j)
            printf("%.15f, ", solvalues[j]);
        printf("\n");
    }
    return 0;
}

#endif
