<?xml version="1.0"?>
<!-- PhantomX Pincher Arm gripper URDF-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:property name="GRIPPER_MAX" value="0.035"/>

    <bioloid_F3_fixed parent="arm_wrist_flex_link" name="arm_wrist_F3_0" color="${color}">
      <origin xyz="0 0 ${F2_HEIGHT}" rpy="0 ${M_PI} ${-M_PI}"/>
    </bioloid_F3_fixed>
    
    <!-- gripper joint -->
    <dynamixel_AX12_fixed parent="arm_wrist_F3_0_link" name="gripper_servo" >
      <origin xyz="0 0 ${-AX12_WIDTH/2}" rpy="${M_PI/2} ${M_PI} ${M_PI/2}"/>
    </dynamixel_AX12_fixed>
    
    <gripper_finger_base parent="gripper_servo_link" name="gripper_finger_base" color="${color}">
        <origin xyz="0 ${AX12_WIDTH/2} 0" rpy="${M_PI} 0 ${M_PI/2}"/>
    </gripper_finger_base>
  
    <!-- Master finger -->
    <!-- NOTE: The transmission for gripper_joint MUST specify a mechnaical reduction of two for
         the gripper seperation to be calculated correctly -->
    <joint name="gripper_joint" type="prismatic">
      <origin xyz="${FINGER_HEIGHT/2} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.05" lower="0.001" upper="${GRIPPER_MAX/2}"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_active_link"/>
    </joint> 
    
    <pincher_gripper name="gripper_active" color="${color}" >
      <origin xyz="0 0.01 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </pincher_gripper>
     
    <!-- Slave finger -->
    <joint name="gripper2_joint" type="prismatic">
      <origin xyz="${FINGER_HEIGHT/2} 0 0" rpy="${M_PI} 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="30" velocity="0.05" lower="0.001" upper="${GRIPPER_MAX/2}"/>
      <parent link="gripper_finger_base_link"/>
      <child link="gripper_active2_link"/>
      <mimic joint="gripper_joint"/>
    </joint>  

    <pincher_gripper name="gripper_active2" color="${color}" >
      <origin xyz="0 0.01 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
    </pincher_gripper>
</robot>
